---
Description: >
  Create an S3 static website, front with a cloudfront distribution pointing at a domain name. 
  Add details to Route53 HostedZone

# Grab some parameters
Parameters:
  domainRoot:
    Type: String
    Description: "The base domain name for the web site (no 'www')"
    MinLength: 4
    MaxLength: 253
    AllowedPattern: "[a-z0-9]+[-.a-z0-9]*(\\.[a-z][a-z]+)+"
    ConstraintDescription: "Provide a valid domain name using only lowercase letters, numbers, and dash (-)"

  domainUrl:
    Type: String
    Description: "The website domain name (if different to the Domain root"
    MinLength: 4
    MaxLength: 253
    AllowedPattern: "[a-z0-9]+[-.a-z0-9]*(\\.[a-z][a-z]+)+"
    ConstraintDescription: "Provide a valid domain name using only lowercase letters, numbers, and dash (-)"

  CertificateARN:
    Type: String
    Description: the Amazon Resource Name (ARN) of an existing AWS Certificate Manager (ACM) certificate.
    AllowedPattern: "arn:aws:acm:.*"

  NotificationEmails:
    Type: String
    Description: Email address to recieve build Notifications
    AllowedPattern: "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$"

  RepoName:
    Type: String
    Description: Name to use for a codecommit repo to hold code for website

  CodeBuildImage:
    Type: String
    Description: Image to use for the codebuild Project
    Default: aws/codebuild/amazonlinux2-x86_64-standard:1.0

  CodeBuildProjectName:
    Type: String
    Description: Name to use for the CodeBuild Project
    # AllowedPattern: "^[A-Za-z0-9][A-Za-z0-9\-_]+$"

# We need a condition to decide if we're a top level domain name or if we're a subdomain
Conditions:
  subdomain: !Not [!Equals [ !Ref domainUrl, "" ]]

# And now some resources - we'll probably end up splitting the HostedZone into a separate template
Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [subdomain, !Ref domainUrl, !Ref domainRoot]
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join [ '', [ 'arn:aws:s3:::', !Ref S3Bucket, '/*']]
      Bucket: !Ref S3Bucket
    DependsOn: S3Bucket

  S3LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '', [ !If [subdomain, !Ref domainUrl, !Ref domainRoot], '-logs' ]]
    DeletionPolicy: Retain

  # CDN to front the S3 bucket - serve over https
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    DependsOn: LogsBucket
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref S3Bucket
        Origins:
          -
            DomainName: !Select [2, !Split ['/', !GetAtt 'S3Bucket.WebsiteURL']]
            Id: RedirectS3Origin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: RedirectS3Origin
          AllowedMethods:
            - GET
            - HEAD
          DefaultTTL: 30
          MinTTL: 5
          ForwardedValues:
            QueryString: false
            Cookies:
             Forward: none
          ViewerProtocolPolicy: allow-all
        Logging:
          Bucket: !Join ['', [ !Ref S3LogBucket, '.s3.amazonaws.com' ]]
          IncludeCookies: false
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateARN
          SslSupportMethod: sni-only
    DependsOn: S3Bucket

  myDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Join [ '', [ !Ref domainRoot, '.' ]]
      Comment: Zone apex alias targetting Cloudfront distribution.
      RecordSets:
      - Name: !If [subdomain, !Ref domainUrl, !Ref domainRoot]
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt CloudFrontDistribution.DomainName
    DependsOn: CloudFrontDistribution

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: Email
          Endpoint: !Ref NotificationEmails

  CodeRepo:
    Type: AWS::CodeCommit::Repository
    Properties: 
      RepositoryName: !Ref RepoName

  CodeBuildIamPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Join [ ' ', [ "Policy to allow codebuild project", !Ref CodeBuildProjectName]]
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: "*"
            Action: 
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
          - Effect: Allow
            Resource:
              - !GetAtt S3Bucket.Arn
              - !Join ['/', [!GetAtt S3Bucket.Arn, '*']]
            Action:
              - s3:PutObject
              - s3:GetBucketAcl
              - s3:GetBucketLocation
          - Effect: Allow
            Resource:
              - !GetAtt CodeRepo.Arn
            Action:
              - codecommit:GitPull

  CodeBuildIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref CodeBuildIamPolicy

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref CodeBuildProjectName
      BadgeEnabled: true
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref CodeBuildImage
        Type: LINUX_CONTAINER
      Source:
        Type: CODECOMMIT
        Location: !GetAtt CodeRepo.CloneUrlHttp
      ServiceRole: !Ref CodeBuildIAMRole
      Artifacts:
        Type: S3
        Location: !Ref S3Bucket


Outputs:
  WebsiteURL:
    Value: !GetAtt S3Bucket.WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt S3Bucket.DomainName
    Description: Name of S3 bucket to hold website content

