---
Description: >
  Create an S3 static website, front with a cloudfront distribution pointing at a domain name. 
  Add details to Route53 HostedZone

# Grab some parameters
Parameters:
  domainRoot:
    Type: String
    Description: "The base domain name for the web site (no 'www')"
    MinLength: 4
    MaxLength: 253
    AllowedPattern: "[a-z0-9]+[-.a-z0-9]*(\\.[a-z][a-z]+)+"
    ConstraintDescription: "Provide a valid domain name using only lowercase letters, numbers, and dash (-)"

  domainUrl:
    Type: String
    Description: "The website domain name (if different to the Domain root"

  CertificateARN:
    Type: String
    Description: the Amazon Resource Name (ARN) of an existing AWS Certificate Manager (ACM) certificate.
    AllowedPattern: "arn:aws:acm:.*"


# We need a condition to decide if we're a top level domain name or if we're a subdomain
Conditions:
  subdomain: !Not [!Equals [ !Ref domainUrl, "" ]]

# And now some resources - we'll probably end up splitting the HostedZone into a separate template
Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [subdomain, !Ref domainUrl, !Ref domainRoot]
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
      Bucket: !Ref S3Bucket

  S3LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '', [ !If [subdomain, !Ref domainUrl, !Ref domainRoot], '-logs' ]]
    DeletionPolicy: Retain

  # CDN to front the S3 bucket - serve over https
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref S3Bucket
        Origins:
          -
            DomainName: !Select [2, !Split ['/', !GetAtt 'S3Bucket.WebsiteURL']]
            Id: RedirectS3Origin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: RedirectS3Origin
          AllowedMethods:
            - GET
            - HEAD
          DefaultTTL: 30
          MinTTL: 5
          ForwardedValues:
            QueryString: false
            Cookies:
             Forward: none
          ViewerProtocolPolicy: allow-all
        Logging:
          Bucket: !Join ['', [ !Ref S3LogBucket, '.s3.amazonaws.com' ]]
          IncludeCookies: false
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateARN
          SslSupportMethod: sni-only

  myDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Join [ '', [ !Ref domainRoot, '.' ]]
      Comment: Zone apex alias targetting Cloudfront distribution.
      RecordSets:
      - Name: !If [subdomain, !Ref domainUrl, !Ref domainRoot]
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt CloudFrontDistribution.DomainName

Outputs:
  S3BucketArn:
    Value: !GetAtt S3Bucket.Arn
    Description: Arn for Static website S3 Bucket
    Export: 
      Name: !Join [':', [ !Ref 'AWS::StackName', S3BucketArn]]
  S3WebsiteURL:
    Value: !GetAtt S3Bucket.WebsiteURL
    Description: URL for website hosted on S3
    Export: 
      Name: !Join [':', [ !Ref 'AWS::StackName', S3WebsiteUrl]]
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt S3Bucket.DomainName
    Description: Name of S3 bucket to hold website content
    Export: 
      Name: !Join [':', [ !Ref 'AWS::StackName', S3BucketSecureURL]]

